### ISSUE TITLE
Seperate active feedback form from other forms

### ISSUE THREAD

**Issue by gekkowrld** [tpauldike/CodeTrybe_Projects#18]
In this repository there are multiple forms that are created. Can the one being used/active i.e **[Feedback form](https://codetrybe.vercel.app/)** as seen [here](https://github.com/codetrybe/CodeTrybe_Projects) in be either placed in it's separate repository or indicated in the **README.md** file. This will make it easier for anyone who wants to contribute to do so.

**Comment by tpauldike** [comment]
Well noted. It's a work in progress. Thank you so much

**Comment by gekkowrld** [comment]
Okay
